package com.ygmy.quicksale.pojo;

import java.util.Date;

public class StaffEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.staff_id
	 * @mbg.generated
	 */
	private Byte staffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.first_name
	 * @mbg.generated
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.last_name
	 * @mbg.generated
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.address_id
	 * @mbg.generated
	 */
	private Short addressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.store_id
	 * @mbg.generated
	 */
	private Byte storeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.active
	 * @mbg.generated
	 */
	private Boolean active;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.last_update
	 * @mbg.generated
	 */
	private Date lastUpdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column staff.picture
	 * @mbg.generated
	 */
	private byte[] picture;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.staff_id
	 * @return  the value of staff.staff_id
	 * @mbg.generated
	 */
	public Byte getStaffId() {
		return staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.staff_id
	 * @param staffId  the value for staff.staff_id
	 * @mbg.generated
	 */
	public void setStaffId(Byte staffId) {
		this.staffId = staffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.first_name
	 * @return  the value of staff.first_name
	 * @mbg.generated
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.first_name
	 * @param firstName  the value for staff.first_name
	 * @mbg.generated
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName == null ? null : firstName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.last_name
	 * @return  the value of staff.last_name
	 * @mbg.generated
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.last_name
	 * @param lastName  the value for staff.last_name
	 * @mbg.generated
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName == null ? null : lastName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.address_id
	 * @return  the value of staff.address_id
	 * @mbg.generated
	 */
	public Short getAddressId() {
		return addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.address_id
	 * @param addressId  the value for staff.address_id
	 * @mbg.generated
	 */
	public void setAddressId(Short addressId) {
		this.addressId = addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.email
	 * @return  the value of staff.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.email
	 * @param email  the value for staff.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.store_id
	 * @return  the value of staff.store_id
	 * @mbg.generated
	 */
	public Byte getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.store_id
	 * @param storeId  the value for staff.store_id
	 * @mbg.generated
	 */
	public void setStoreId(Byte storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.active
	 * @return  the value of staff.active
	 * @mbg.generated
	 */
	public Boolean getActive() {
		return active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.active
	 * @param active  the value for staff.active
	 * @mbg.generated
	 */
	public void setActive(Boolean active) {
		this.active = active;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.username
	 * @return  the value of staff.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.username
	 * @param username  the value for staff.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.password
	 * @return  the value of staff.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.password
	 * @param password  the value for staff.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.last_update
	 * @return  the value of staff.last_update
	 * @mbg.generated
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.last_update
	 * @param lastUpdate  the value for staff.last_update
	 * @mbg.generated
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column staff.picture
	 * @return  the value of staff.picture
	 * @mbg.generated
	 */
	public byte[] getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column staff.picture
	 * @param picture  the value for staff.picture
	 * @mbg.generated
	 */
	public void setPicture(byte[] picture) {
		this.picture = picture;
	}
}